Feat/webapp/new game
Arquisoft/wiq_en2b pull request #102
Opened 2024-03-09 16:52 UTC by sergiorodriguezgarcia

2024-03-09 18:54 UTC, Toto-hitori approved these changes

2024-03-09 18:54 UTC, Toto-hitori commented on webapp/src/pages/Game.jsx
> +		setAnswer(question.answers[option]);
ejem you need to do (option-1) since options start at 1 and end at 2 so it will give an index out of bounds error :)

2024-03-09 18:55 UTC, Toto-hitori commented
Add tests please

2024-03-10 12:07 UTC, uo283928 approved these changes

2024-03-10 18:57 UTC, Toto-hitori requested changes

2024-03-10 18:57 UTC, Toto-hitori commented on docker-compose.yml
> +    image: ghcr.io/arquisoft/wiq_en2b/webapp:latest
remove this line, it is not necessary

2024-03-10 18:58 UTC, Toto-hitori approved these changes

2024-03-10 19:03 UTC, merged