Hotfix/question language
Arquisoft/wiq_en2b pull request #104
Opened 2024-03-10 11:01 UTC by sergioqfeg1

Added the lang parameter for the questions to appear in one language (English by default)

2024-03-10 18:30 UTC, Toto-hitori requested changes

2024-03-10 18:30 UTC, Toto-hitori commented on api/src/main/java/lab/en2b/quizapi/questions/question/QuestionService.java
Please remove the getQuestions method <3

2024-03-11 08:50 UTC, Toto-hitori approved these changes

2024-03-11 09:02 UTC, gony02 approved these changes
Good job!!!

2024-03-11 09:02 UTC, merged