Feat/webapp/new login
Arquisoft/wiq_en2b pull request #64
Opened 2024-03-01 17:57 UTC by gony02

Creating the login view with the corresponding tests and internationalisation. Two of the tests cannot pass.

2024-03-01 18:09 UTC, sergiorodriguezgarcia approved these changes
All seems to be correct.

2024-03-03 00:50 UTC, jjgancfer commented
I'm currently waiting for the bug in #69 to be solved, as I cannot work towards fixing the test that fails without it. I'll approve when it is.

2024-03-03 12:12 UTC, jjgancfer requested changes

2024-03-03 12:12 UTC, jjgancfer commented on webapp/src/pages/Login.jsx
> +                            <Text>Error</Text>
This error message does not seem to be localized. It is also quite generic, so please change it.

2024-03-03 13:49 UTC, jjgancfer approved these changes
The requested changes seem to have been included. Approved.

2024-03-03 13:49 UTC, merged