Feat/webapp/new signup
Arquisoft/wiq_en2b pull request #65
Opened 2024-03-01 18:08 UTC by sergiorodriguezgarcia

Implementation of the Signup view with the corresponding tests, two of them can not pass because of the comunication with the backend.

2024-03-01 18:15 UTC, gony02 approved these changes
Everything seems to be OK 👍

2024-03-03 00:48 UTC, jjgancfer requested changes

2024-03-03 00:48 UTC, jjgancfer commented on webapp/src/pages/Signup.jsx
> +import { FaUserAlt, FaLock, FaAddressCard } from "react-icons/fa";
The tests seem to fail on this line. Please, try to fix it.

2024-03-04 20:59 UTC, jjgancfer approved these changes
It seems it works now. Approved and merged.

2024-03-04 20:59 UTC, merged