Feat: Questions and answers are now written in the DB!
Arquisoft/wiq_en2b pull request #97
Opened 2024-03-08 16:54 UTC by UO283615

Now the questions are written in the DB, this is done by a new module.
Tests are yet to be done, but we wanted to upload this to have the application working with the wikidata questions.
We also need to write the architecturals decissions involved with this part.

2024-03-08 18:07 UTC, uo283928 commented
As we have discussed with @Toto-hitori, tests are meaningless as this code is just for DB connections and JPA models so they are discarded.
I think this code is fine for now, but in the future we may have problems with the current version of QuestionTemplate.call() in case we implement question types which require more than one query. We can start thinking about a solution for next versions but I would leave it as it is for now.

2024-03-08 18:08 UTC, uo283928 approved these changes

2024-03-08 21:57 UTC, Toto-hitori requested changes

2024-03-08 21:57 UTC, Toto-hitori commented on questiongenerator/.mvn/wrapper/maven-wrapper.jar
Remove this

2024-03-08 21:57 UTC, Toto-hitori commented on questiongenerator/.mvn/wrapper/maven-wrapper.properties
And this

2024-03-09 13:35 UTC, Toto-hitori approved these changes

2024-03-09 13:36 UTC, merged